CREATE TABLE IF NOT EXISTS Currencies(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(3) UNIQUE NOT NULL,
    full_name varchar(30) NOT NULL,
    sign varchar(3) NOT NULL
);
